language: go
go:
  - 1.8.1
services:
  - docker
before_install:
  - cd $HOME/gopath/src/
  - git clone --depth=50 --branch=master https://github.com/zainul-ma/customer-template.git customer
  - cd $HOME/gopath/src/customer
install:
  - wget https://raw.githubusercontent.com/pote/gpm/v1.4.0/bin/gpm && chmod +x gpm && sudo mv gpm /usr/local/bin
  - go get -u gopkg.in/alecthomas/gometalinter.v1
  - go get github.com/mattn/goveralls
  - gpm install
script:
  - cd $HOME/gopath/
  - ls -lah
  - cd $HOME/gopath/src/customer
  - ls -lah
  - go env
  - pwd
  - cd tests && go test ./...
  - cd $HOME/gopath/src/customer
  - gometalinter --vendor ./...
  # - $HOME/gopath/bin/goveralls -service=travis-ci
# after_success:
  # - docker build -t apalahitunamanya2/blog .
  # - if [ "$TRAVIS_BRANCH" == "master" ]; then
  #   docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  #   docker push apalahitunamanya2/blog;
  #   fi
# notifications:
#   slack:
#     rooms:
#       - tnindo:UQ4e43faD5fHRZOuDEoWoF88#travis-ci
